# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: SkyHive's Blog
subtitle:
description: 莫听穿林打叶声，何妨吟啸且徐行
author: SkyHive
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://skyhive.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: categorized
category_map:
	
    Blog: Blog

    Code: Code
	
    运维: Infra

    数据结构与算法: Algorithm
	
    生活: 生活

tag_map:

sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml
# Social links
social:
  GitHub: https://github.com/SkyHive
  Weibo: http://weibo.com/1612736643/profile?rightmod=1&wvr=6&mod=personinfo&is_all=1
  Facebook: https://www.facebook.com/profile.php?id=100011441371544
  知乎: https://www.zhihu.com/people/yang-zhong-yi-57/activities
# Search
search:
    path: search.xml
    field: post
    format: html
    limit: 10000

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

#plugins:
#
# RSS订阅支持
plugin:
- hexo-generator-feed

# Feed Atom
feed:
type: atom
path: atom.xml
limit: 20
content_limit: 140
content_limit_delim: ' '
order_by: -date
autodiscovery: true
template:
#- hexo-qiniu-sync

#qiniu:
#  offline: false
#  sync: true
#  bucket: skyhive-blog
#  access_key: WHGjx2q-9FCQ4tn1lKBTk9m2XKJl7-eWqnk1j4lu
#  secret_key: 7cNco0zVDPBdICudWRG5wWmcFoLUoo9MhEkpjq_S
#  dirPrefix:
#  urlPrefix: http://old5ws7lp.bkt.clouddn.com
#  local_dir: picture
#  update_exist: true
#  image:
#    folder: images
#    extend:
#  js:
#    folder: js
#  css: 
#    folder: css
#
# hexo-filter-plugin (https://github.com/Jamling/hexo-filter-highlight) config 
## highlight in frontend, the plugin (backend) just do some prepare work.
## you need to read the docs on https://github.com/Jamling/hexo-filter-highlight to getting start
hljs:
  enable: false #true to enable the plugin
  line_number: frontend # add line_number in frontend or backend
  trim_indent: backend # trim the indent of code block to prettify output. backend or front-end (recommend)
  copy_code: true # show copy code in caption.
  label:
    left: Code
    right: ':'
    copy: Copy Code

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: git@github.com:SkyHive/SkyHive.github.io.git
  branch: master
